# Dockerfile (frontend)

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html

# Xóa các file mặc định của nginx
RUN rm -rf ./*

# Chỉ copy thư mục build vào
COPY build/ .

# Mặc định dùng nginx để serve static
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
