version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pharmacy_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=pharmacy.settings
      - POSTGRES_DB=pharmacy
      - POSTGRES_USER=pharmacy
      - POSTGRES_PASSWORD=pharmacy
      - POSTGRES_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: pharmacy_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: pharmacy_db
    environment:
      POSTGRES_DB: pharmacy
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: